name: tradegood
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
  flutter_secure_storage: ^4.2.0
  intl: ^0.17.0
  pin_code_fields: ^7.2.0
  connectivity: ^3.0.6
  shared_preferences: ^2.0.6
  cupertino_icons: ^0.1.3
  flutter_svg: ^0.22.0
  carousel_slider: ^4.0.0-nullsafety.0
  modal_bottom_sheet: ^2.0.0
  jwt_decoder: ^2.0.1
  toast:
    git:
      url: https://github.com/appdev/FlutterToast.git
  move_to_background: any
  dio: ^4.0.0
  frefresh: any
  url_launcher: ^6.0.6
  smooth_star_rating: 1.1.1
  flutter_native_image: ^0.0.6
  image_picker: ^0.8.0+3
dependency_overrides:
  flutter_offline: 2.0.0
  connectivity: ^3.0.6
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/images2/
    - assets/logo/
    - assets/

  fonts:
    - family: Muli
      fonts:
        - asset: assets/fonts/muli/Muli.ttf
        - asset: assets/fonts/muli/Muli-Bold.ttf
          weight: 700
        - asset: assets/fonts/muli/Muli-Light.ttf
          weight: 300

